package outboxer

import (
	"context"
	"database/sql"
	"os"
	"testing"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/stdlib"
)

// TestBatchedDeadLetterInsertAgainstPostgres exercises the batched
// unnest($1::text[])::jsonb dead-letter insert through the real driver, which
// sqlmock cannot verify.
func TestBatchedDeadLetterInsertAgainstPostgres(t *testing.T) {
	dsn := os.Getenv("OUTBOXER_INTEGRATION_PG_DSN")
	if dsn == "" {
		t.Skip("set OUTBOXER_INTEGRATION_PG_DSN to run the Postgres integration test")
	}
	pgConfig, err := pgx.ParseConfig(dsn)
	if err != nil {
		t.Fatalf("parse DSN: %v", err)
	}
	db := stdlib.OpenDB(*pgConfig)
	defer db.Close()

	ctx := context.Background()
	if _, err := db.ExecContext(ctx, `CREATE TABLE IF NOT EXISTS dlq_batch_check (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, event jsonb NOT NULL)`); err != nil {
		t.Fatalf("create table: %v", err)
	}
	defer func() { _, _ = db.ExecContext(ctx, `DROP TABLE dlq_batch_check`) }()

	cfg := testConfig()
	cfg.DLQTable = "dlq_batch_check"
	a := &app{cfg: cfg, db: db}

	tx, err := db.BeginTx(ctx, nil)
	if err != nil {
		t.Fatalf("begin: %v", err)
	}
	poison := []poisonEvent{
		{evt: event{columns: map[string]any{"id": "p-1", "payload": "one"}, route: eventRoute{target: "pubsub", destination: "t"}}, error: "bad one"},
		{evt: event{columns: map[string]any{"id": "p-2", "payload": "two"}, route: eventRoute{target: "sqs", destination: "q"}}, error: "bad two"},
	}
	if err := a.insertDeadLetters(ctx, tx, poison); err != nil {
		t.Fatalf("insertDeadLetters: %v", err)
	}
	if err := tx.Commit(); err != nil {
		t.Fatalf("commit: %v", err)
	}

	var count int
	var ids sql.NullString
	if err := db.QueryRowContext(ctx, `SELECT count(*), string_agg(event->'original_event'->>'id', ',' ORDER BY event->'original_event'->>'id') FROM dlq_batch_check`).Scan(&count, &ids); err != nil {
		t.Fatalf("verify: %v", err)
	}
	if count != 2 || ids.String != "p-1,p-2" {
		t.Fatalf("expected 2 dead letters p-1,p-2; got count=%d ids=%q", count, ids.String)
	}
}
