package outboxer

import (
	"context"
	"crypto/rand"
	"database/sql"
	"errors"
	"flag"
	"fmt"
	"log/slog"
	"os"
	"strings"
	"time"

	"github.com/fvdsn/outboxer/internal/outboxer/provider"
)

// runInit provisions the database objects the relay needs. Without --apply it
// prints the generated SQL to stdout (no database connection); with --apply it
// executes the SQL in a single transaction and validates the result before
// committing.
func runInit(ctx context.Context, args []string) error {
	cfg, apply, err := loadInitConfig(args, os.Stderr)
	if err != nil {
		if errors.Is(err, flag.ErrHelp) {
			return nil
		}
		return fmt.Errorf("invalid configuration: %w", err)
	}

	setupLogging(cfg.LogLevel, cfg.LogFormat)

	if err := cfg.validate(configValidationInit); err != nil {
		return fmt.Errorf("invalid configuration: %w", err)
	}

	if !apply {
		// Print mode never connects and never reveals the run-role password.
		fmt.Print(renderInitScript(buildInitStatements(cfg, true)))
		return nil
	}

	return applyInit(ctx, cfg)
}

// initStatement is one SQL statement plus an optional comment shown only in
// printed output.
type initStatement struct {
	comment string
	sql     string
}

// buildInitStatements returns the ordered provisioning statements for the given
// configuration. When redactSecrets is true (print mode) the run-role password
// is emitted as PASSWORD NULL; otherwise the real password is interpolated.
func buildInitStatements(cfg appConfig, redactSecrets bool) []initStatement {
	manageRoles := cfg.PGInitUser != ""

	var stmts []initStatement
	if manageRoles {
		stmts = append(stmts, runRoleStatement(cfg, redactSecrets))
	}

	stmts = append(stmts, initStatement{sql: createSchemaSQL(cfg)})
	stmts = append(stmts, initStatement{sql: createEventTableSQL(cfg)})
	if cfg.DLQTable != "" {
		stmts = append(stmts, initStatement{sql: createDLQTableSQL(cfg)})
	}
	// The notification trigger is always provisioned, independent of
	// POLL_INTERVAL_MS. Provisioning is a one-time operation while the poll
	// interval is a relay-runtime setting; installing the trigger unconditionally
	// lets an operator enable LISTEN/NOTIFY wake-ups later without re-running init.
	// The trigger is a cheap statement-level pg_notify that is simply discarded
	// when no relay is listening.
	stmts = append(stmts, notifyFunctionStatement(cfg))
	stmts = append(stmts, notifyTriggerStatements(cfg)...)

	if manageRoles {
		stmts = append(stmts, runRoleGrantStatements(cfg)...)
		stmts = append(stmts, producerGrantStatements(cfg)...)
	}
	return stmts
}

func createSchemaSQL(cfg appConfig) string {
	return fmt.Sprintf("CREATE SCHEMA IF NOT EXISTS %s;", ident(cfg.PGSchema))
}

func createEventTableSQL(cfg appConfig) string {
	columns := []string{
		fmt.Sprintf("%s bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", ident(cfg.EventID)),
		fmt.Sprintf("%s text NOT NULL", ident(cfg.EventPayload)),
	}
	// Optional columns are created whenever their name is configured (non-empty),
	// regardless of backend/feature flags. An empty name disables the column.
	if cfg.EventTarget != "" {
		columns = append(columns, fmt.Sprintf("%s text", ident(cfg.EventTarget)))
	}
	if cfg.EventDestination != "" {
		columns = append(columns, fmt.Sprintf("%s text", ident(cfg.EventDestination)))
	}
	if cfg.EventTimestamp != "" {
		columns = append(columns, fmt.Sprintf("%s timestamptz", ident(cfg.EventTimestamp)))
	}
	if cfg.EventOptions != "" {
		columns = append(columns, fmt.Sprintf("%s jsonb", ident(cfg.EventOptions)))
	}
	return fmt.Sprintf("CREATE TABLE IF NOT EXISTS %s (\n    %s\n);", qualifiedIdent(cfg.PGSchema, cfg.EventTable), strings.Join(columns, ",\n    "))
}

func createDLQTableSQL(cfg appConfig) string {
	return fmt.Sprintf(
		"CREATE TABLE IF NOT EXISTS %s (\n    %s bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n    %s jsonb NOT NULL\n);",
		qualifiedIdent(cfg.PGSchema, cfg.DLQTable), ident("id"), ident("event"),
	)
}

func notifyFunctionStatement(cfg appConfig) initStatement {
	return initStatement{sql: fmt.Sprintf("CREATE OR REPLACE FUNCTION %s() RETURNS trigger AS $$\n", qualifiedIdent(cfg.PGSchema, "outboxer_notify")) +
		"BEGIN\n" +
		"  PERFORM pg_notify(TG_ARGV[0], '');\n" +
		"  RETURN NULL;\n" +
		"END;\n" +
		"$$ LANGUAGE plpgsql;"}
}

func notifyTriggerStatements(cfg appConfig) []initStatement {
	table := qualifiedIdent(cfg.PGSchema, cfg.EventTable)
	function := qualifiedIdent(cfg.PGSchema, "outboxer_notify")
	return []initStatement{
		{sql: fmt.Sprintf("DROP TRIGGER IF EXISTS outboxer_notify ON %s;", table)},
		{sql: fmt.Sprintf(
			"CREATE TRIGGER outboxer_notify\nAFTER INSERT ON %s\nFOR EACH STATEMENT\nEXECUTE FUNCTION %s(%s);",
			table, function, sqlStringLiteral(cfg.NotifyChannel),
		)},
	}
}

func runRoleStatement(cfg appConfig, redactSecrets bool) initStatement {
	password := "NULL"
	comment := ""
	if redactSecrets {
		comment = "-- Configure authentication for the run role separately before starting Outboxer."
	} else if cfg.PGPassword != "" {
		password = sqlStringLiteral(cfg.PGPassword)
	}
	tag := "$outboxer_" + rand.Text() + "$"
	sql := fmt.Sprintf("DO %s BEGIN\n"+
		"  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = %s) THEN\n"+
		"    CREATE ROLE %s LOGIN PASSWORD %s;\n"+
		"  END IF;\n"+
		"END %s;",
		tag, sqlStringLiteral(cfg.PGUser), ident(cfg.PGUser), password, tag)
	return initStatement{comment: comment, sql: sql}
}

func runRoleGrantStatements(cfg appConfig) []initStatement {
	run := ident(cfg.PGUser)
	table := qualifiedIdent(cfg.PGSchema, cfg.EventTable)
	stmts := []initStatement{
		{sql: fmt.Sprintf("GRANT USAGE ON SCHEMA %s TO %s;", ident(cfg.PGSchema), run)},
		{sql: fmt.Sprintf("GRANT SELECT, DELETE ON %s TO %s;", table, run)},
		{sql: fmt.Sprintf("GRANT UPDATE (%s) ON %s TO %s;", ident(cfg.EventID), table, run)},
	}
	if cfg.DLQTable != "" {
		stmts = append(stmts, initStatement{sql: fmt.Sprintf("GRANT INSERT ON %s TO %s;", qualifiedIdent(cfg.PGSchema, cfg.DLQTable), run)})
	}
	return stmts
}

func producerGrantStatements(cfg appConfig) []initStatement {
	table := qualifiedIdent(cfg.PGSchema, cfg.EventTable)
	stmts := make([]initStatement, 0, 2*len(cfg.PGProducerRoles))
	for _, role := range cfg.PGProducerRoles {
		quotedRole := ident(role)
		stmts = append(stmts,
			initStatement{sql: fmt.Sprintf("GRANT USAGE ON SCHEMA %s TO %s;", ident(cfg.PGSchema), quotedRole)},
			initStatement{sql: fmt.Sprintf("GRANT SELECT, INSERT ON %s TO %s;", table, quotedRole)},
		)
	}
	return stmts
}

func renderInitScript(stmts []initStatement) string {
	var b strings.Builder
	for i, s := range stmts {
		if i > 0 {
			b.WriteString("\n\n")
		}
		if s.comment != "" {
			b.WriteString(s.comment)
			b.WriteString("\n")
		}
		b.WriteString(s.sql)
	}
	b.WriteString("\n")
	return b.String()
}

// applyInit executes the provisioning statements in a single transaction. When
// PG_INIT_USER is set it connects as that provisioning role; otherwise it
// connects as the run role and only creates schema objects. After applying the
// DDL it validates the resulting table shapes and rolls back on any mismatch.
func applyInit(ctx context.Context, cfg appConfig) error {
	connCfg := cfg
	if cfg.PGInitUser != "" {
		connCfg.PGUser = cfg.PGInitUser
		connCfg.PGPassword = cfg.PGInitPassword
	}

	db, err := openDB(connCfg)
	if err != nil {
		return fmt.Errorf("open database: %w", err)
	}
	defer db.Close()

	tx, err := db.BeginTx(ctx, nil)
	if err != nil {
		return fmt.Errorf("begin transaction: %w", err)
	}
	defer func() { _ = tx.Rollback() }()

	for _, stmt := range buildInitStatements(cfg, false) {
		if err := execInitStatement(ctx, tx, cfg.PGQueryTimeout, stmt.sql); err != nil {
			return fmt.Errorf("apply provisioning statement: %w", err)
		}
	}

	if err := validateProvisionedSchema(ctx, tx, cfg); err != nil {
		return fmt.Errorf("post-apply validation: %w", err)
	}

	// tx.Commit takes no context (matching the relay), so it is not bounded by
	// PG_QUERY_TIMEOUT; BeginTx uses the parent context because that context
	// governs the whole transaction's lifetime.
	if err := tx.Commit(); err != nil {
		return fmt.Errorf("commit: %w", err)
	}

	slog.Info("Provisioning applied", "event_table", cfg.EventTable, "dlq_table", cfg.DLQTable)
	return nil
}

// execInitStatement runs a single provisioning statement bounded by
// PG_QUERY_TIMEOUT, so a conflicting lock cannot hang provisioning indefinitely.
func execInitStatement(ctx context.Context, tx *sql.Tx, timeout time.Duration, query string) error {
	ctx, cancel := provider.WithTimeout(ctx, timeout)
	defer cancel()
	_, err := tx.ExecContext(ctx, query)
	return err
}

// validateProvisionedSchema runs the relay's own shape checks against the
// uncommitted transaction, so a successful apply guarantees a relay-ready schema.
func validateProvisionedSchema(ctx context.Context, tx *sql.Tx, cfg appConfig) error {
	columnsCtx, cancel := provider.WithTimeout(ctx, cfg.PGQueryTimeout)
	defer cancel()
	rows, err := tx.QueryContext(columnsCtx, fmt.Sprintf("SELECT * FROM %s LIMIT 0", qualifiedIdent(cfg.PGSchema, cfg.EventTable)))
	if err != nil {
		return err
	}
	columns, err := rows.Columns()
	_ = rows.Close()
	if err != nil {
		return err
	}

	if err := validateEventColumns(cfg, columns); err != nil {
		return err
	}

	if cfg.DLQTable != "" {
		dlqCtx, cancel := provider.WithTimeout(ctx, cfg.PGQueryTimeout)
		defer cancel()
		metadata, err := loadDLQTableMetadata(dlqCtx, tx, cfg.PGSchema, cfg.DLQTable)
		if err != nil {
			return err
		}
		if err := validateDLQTableMetadata(cfg.DLQTable, metadata); err != nil {
			return err
		}
	}
	return nil
}
