package outboxer

import (
	"context"
	"database/sql"
	"errors"
	"flag"
	"fmt"
	"log/slog"
	"os"
	"strings"
)

// runInit provisions the database objects the relay needs. Without --apply it
// prints the generated SQL to stdout (no database connection); with --apply it
// executes the SQL in a single transaction and validates the result before
// committing.
func runInit(ctx context.Context, args []string) error {
	cfg, apply, err := loadInitConfig(args, os.Stderr)
	if err != nil {
		if errors.Is(err, flag.ErrHelp) {
			return nil
		}
		return fmt.Errorf("invalid configuration: %w", err)
	}

	setupLogging(cfg.LogLevel, cfg.LogFormat)

	if err := validateInitConfig(cfg); err != nil {
		return fmt.Errorf("invalid configuration: %w", err)
	}

	if !apply {
		// Print mode never connects and never reveals the run-role password.
		fmt.Print(renderInitScript(buildInitStatements(cfg, true)))
		return nil
	}

	return applyInit(ctx, cfg)
}

// validateInitConfig checks the configuration subset init needs to generate the
// schema. It does not require a publishing backend, since provisioning is
// independent of where events are later sent.
func validateInitConfig(cfg appConfig) error {
	if cfg.EventTable == "" {
		return fmt.Errorf("an event table is required: set EVENT_TABLE")
	}
	if cfg.EventID == "" {
		return fmt.Errorf("an id column is required: set EVENT_ID")
	}
	if cfg.EventPayload == "" {
		return fmt.Errorf("a payload column is required: set EVENT_PAYLOAD")
	}
	if cfg.DLQTable != "" && cfg.DLQTable == cfg.EventTable {
		return fmt.Errorf("DLQ_TABLE must not equal EVENT_TABLE")
	}
	if cfg.PollInterval > 0 && cfg.NotifyChannel == "" {
		return fmt.Errorf("notify channel must not be empty when polling is enabled: set NOTIFY_CHANNEL or POLL_INTERVAL_MS=0")
	}

	// Two configured, non-empty columns resolving to the same name would generate
	// duplicate table columns.
	seen := map[string]string{}
	columns := []struct{ value, label string }{
		{cfg.EventID, "EVENT_ID"},
		{cfg.EventPayload, "EVENT_PAYLOAD"},
		{cfg.EventTarget, "EVENT_TARGET"},
		{cfg.EventDestination, "EVENT_DESTINATION"},
		{cfg.EventTimestamp, "EVENT_TIMESTAMP"},
		{cfg.EventOptions, "EVENT_OPTIONS"},
	}
	for _, column := range columns {
		if column.value == "" {
			continue
		}
		if prev, ok := seen[column.value]; ok {
			return fmt.Errorf("%s and %s both resolve to the same column name %q", prev, column.label, column.value)
		}
		seen[column.value] = column.label
	}
	return nil
}

// initStatement is one SQL statement plus an optional comment shown only in
// printed output.
type initStatement struct {
	comment string
	sql     string
}

// buildInitStatements returns the ordered provisioning statements for the given
// configuration. When redactSecrets is true (print mode) the run-role password
// is emitted as PASSWORD NULL; otherwise the real password is interpolated.
func buildInitStatements(cfg appConfig, redactSecrets bool) []initStatement {
	manageRoles := cfg.PGInitUser != ""

	var stmts []initStatement
	if manageRoles {
		stmts = append(stmts, runRoleStatement(cfg, redactSecrets))
	}

	stmts = append(stmts, initStatement{sql: createEventTableSQL(cfg)})
	if cfg.DLQTable != "" {
		stmts = append(stmts, initStatement{sql: createDLQTableSQL(cfg)})
	}
	if cfg.PollInterval > 0 {
		stmts = append(stmts, notifyFunctionStatement())
		stmts = append(stmts, notifyTriggerStatements(cfg)...)
	}

	if manageRoles {
		stmts = append(stmts, runRoleGrantStatements(cfg)...)
		stmts = append(stmts, producerGrantStatements(cfg)...)
	}
	return stmts
}

func createEventTableSQL(cfg appConfig) string {
	columns := []string{
		fmt.Sprintf("%s bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", ident(cfg.EventID)),
		fmt.Sprintf("%s text NOT NULL", ident(cfg.EventPayload)),
	}
	// Optional columns are created whenever their name is configured (non-empty),
	// regardless of backend/feature flags. An empty name disables the column.
	if cfg.EventTarget != "" {
		columns = append(columns, fmt.Sprintf("%s text", ident(cfg.EventTarget)))
	}
	if cfg.EventDestination != "" {
		columns = append(columns, fmt.Sprintf("%s text", ident(cfg.EventDestination)))
	}
	if cfg.EventTimestamp != "" {
		columns = append(columns, fmt.Sprintf("%s timestamptz", ident(cfg.EventTimestamp)))
	}
	if cfg.EventOptions != "" {
		columns = append(columns, fmt.Sprintf("%s jsonb", ident(cfg.EventOptions)))
	}
	return fmt.Sprintf("CREATE TABLE IF NOT EXISTS %s (\n    %s\n);", ident(cfg.EventTable), strings.Join(columns, ",\n    "))
}

func createDLQTableSQL(cfg appConfig) string {
	return fmt.Sprintf(
		"CREATE TABLE IF NOT EXISTS %s (\n    %s bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n    %s jsonb NOT NULL\n);",
		ident(cfg.DLQTable), ident("id"), ident("event"),
	)
}

func notifyFunctionStatement() initStatement {
	return initStatement{sql: "CREATE OR REPLACE FUNCTION outboxer_notify() RETURNS trigger AS $$\n" +
		"BEGIN\n" +
		"  PERFORM pg_notify(TG_ARGV[0], '');\n" +
		"  RETURN NULL;\n" +
		"END;\n" +
		"$$ LANGUAGE plpgsql;"}
}

func notifyTriggerStatements(cfg appConfig) []initStatement {
	table := ident(cfg.EventTable)
	return []initStatement{
		{sql: fmt.Sprintf("DROP TRIGGER IF EXISTS outboxer_notify ON %s;", table)},
		{sql: fmt.Sprintf(
			"CREATE TRIGGER outboxer_notify\nAFTER INSERT ON %s\nFOR EACH STATEMENT\nEXECUTE FUNCTION outboxer_notify(%s);",
			table, sqlStringLiteral(cfg.NotifyChannel),
		)},
	}
}

func runRoleStatement(cfg appConfig, redactSecrets bool) initStatement {
	password := "NULL"
	comment := ""
	if redactSecrets {
		comment = "-- Configure authentication for the run role separately before starting Outboxer."
	} else if cfg.PGPassword != "" {
		password = sqlStringLiteral(cfg.PGPassword)
	}
	sql := fmt.Sprintf("DO $$ BEGIN\n"+
		"  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = %s) THEN\n"+
		"    CREATE ROLE %s LOGIN PASSWORD %s;\n"+
		"  END IF;\n"+
		"END $$;",
		sqlStringLiteral(cfg.PGUser), ident(cfg.PGUser), password)
	return initStatement{comment: comment, sql: sql}
}

func runRoleGrantStatements(cfg appConfig) []initStatement {
	run := ident(cfg.PGUser)
	table := ident(cfg.EventTable)
	stmts := []initStatement{
		{sql: fmt.Sprintf("GRANT USAGE ON SCHEMA public TO %s;", run)},
		{sql: fmt.Sprintf("GRANT SELECT, DELETE ON %s TO %s;", table, run)},
		{sql: fmt.Sprintf("GRANT UPDATE (%s) ON %s TO %s;", ident(cfg.EventID), table, run)},
	}
	if cfg.DLQTable != "" {
		stmts = append(stmts, initStatement{sql: fmt.Sprintf("GRANT INSERT ON %s TO %s;", ident(cfg.DLQTable), run)})
	}
	return stmts
}

func producerGrantStatements(cfg appConfig) []initStatement {
	table := ident(cfg.EventTable)
	stmts := make([]initStatement, 0, len(cfg.PGProducerRoles))
	for _, role := range cfg.PGProducerRoles {
		stmts = append(stmts, initStatement{sql: fmt.Sprintf("GRANT SELECT, INSERT ON %s TO %s;", table, ident(role))})
	}
	return stmts
}

func renderInitScript(stmts []initStatement) string {
	var b strings.Builder
	for i, s := range stmts {
		if i > 0 {
			b.WriteString("\n\n")
		}
		if s.comment != "" {
			b.WriteString(s.comment)
			b.WriteString("\n")
		}
		b.WriteString(s.sql)
	}
	b.WriteString("\n")
	return b.String()
}

// applyInit executes the provisioning statements in a single transaction. When
// PG_INIT_USER is set it connects as that provisioning role; otherwise it
// connects as the run role and only creates schema objects. After applying the
// DDL it validates the resulting table shapes and rolls back on any mismatch.
func applyInit(ctx context.Context, cfg appConfig) error {
	connCfg := cfg
	if cfg.PGInitUser != "" {
		connCfg.PGUser = cfg.PGInitUser
		connCfg.PGPassword = cfg.PGInitPassword
	}

	db, err := openDB(connCfg)
	if err != nil {
		return fmt.Errorf("open database: %w", err)
	}
	defer db.Close()

	tx, err := db.BeginTx(ctx, nil)
	if err != nil {
		return fmt.Errorf("begin transaction: %w", err)
	}
	defer func() { _ = tx.Rollback() }()

	for _, stmt := range buildInitStatements(cfg, false) {
		if _, err := tx.ExecContext(ctx, stmt.sql); err != nil {
			return fmt.Errorf("apply provisioning statement: %w", err)
		}
	}

	if err := validateProvisionedSchema(ctx, tx, cfg); err != nil {
		return fmt.Errorf("post-apply validation: %w", err)
	}

	if err := tx.Commit(); err != nil {
		return fmt.Errorf("commit: %w", err)
	}

	slog.Info("Provisioning applied", "event_table", cfg.EventTable, "dlq_table", cfg.DLQTable)
	return nil
}

// validateProvisionedSchema runs the relay's own shape checks against the
// uncommitted transaction, so a successful apply guarantees a relay-ready schema.
func validateProvisionedSchema(ctx context.Context, tx *sql.Tx, cfg appConfig) error {
	rows, err := tx.QueryContext(ctx, fmt.Sprintf("SELECT * FROM %s LIMIT 0", ident(cfg.EventTable)))
	if err != nil {
		return err
	}
	columns, err := rows.Columns()
	_ = rows.Close()
	if err != nil {
		return err
	}

	checker := &app{cfg: cfg}
	if err := checker.checkRequiredColumns(columns); err != nil {
		return err
	}

	if cfg.DLQTable != "" {
		metadata, err := loadDLQTableMetadata(ctx, tx, cfg.DLQTable)
		if err != nil {
			return err
		}
		if err := validateDLQTableMetadata(cfg.DLQTable, metadata); err != nil {
			return err
		}
	}
	return nil
}
