package outboxer

import (
	"context"
	"io"
	"reflect"
	"strings"
	"testing"
	"time"
)

func baselineInitConfig() appConfig {
	return appConfig{
		EventTable:       "events",
		EventID:          "id",
		EventPayload:     "payload",
		EventTarget:      "target",
		EventDestination: "destination",
		EventTimestamp:   "timestamp",
		EventOptions:     "options",
		PGUser:           "outboxer",
		PGPassword:       "s3cret",
		NotifyChannel:    "outboxer_events",
	}
}

func initScript(cfg appConfig, redactSecrets bool) string {
	return renderInitScript(buildInitStatements(cfg, redactSecrets))
}

func assertContains(t *testing.T, script, substr string) {
	t.Helper()
	if !strings.Contains(script, substr) {
		t.Fatalf("expected script to contain %q\n--- script ---\n%s", substr, script)
	}
}

func assertNotContains(t *testing.T, script, substr string) {
	t.Helper()
	if strings.Contains(script, substr) {
		t.Fatalf("expected script NOT to contain %q\n--- script ---\n%s", substr, script)
	}
}

func TestInitScriptCreatesAllConfiguredColumns(t *testing.T) {
	script := initScript(baselineInitConfig(), true)

	assertContains(t, script, `CREATE TABLE IF NOT EXISTS "events"`)
	assertContains(t, script, `"id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY`)
	assertContains(t, script, `"payload" text NOT NULL`)
	assertContains(t, script, `"target" text`)
	assertContains(t, script, `"destination" text`)
	assertContains(t, script, `"timestamp" timestamptz`)
	assertContains(t, script, `"options" jsonb`)
}

func TestInitScriptOmitsEmptyOptionalColumns(t *testing.T) {
	cfg := baselineInitConfig()
	cfg.EventOptions = ""
	cfg.EventTarget = ""

	script := initScript(cfg, true)

	assertNotContains(t, script, `"options"`)
	assertNotContains(t, script, `"target"`)
	// Other configured columns remain.
	assertContains(t, script, `"destination" text`)
	assertContains(t, script, `"timestamp" timestamptz`)
}

func TestInitScriptNoRolesWithoutInitUser(t *testing.T) {
	script := initScript(baselineInitConfig(), true)

	assertNotContains(t, script, "CREATE ROLE")
	assertNotContains(t, script, "GRANT")
}

func TestInitScriptManagesRunRoleWithInitUser(t *testing.T) {
	cfg := baselineInitConfig()
	cfg.PGInitUser = "admin"

	script := initScript(cfg, true)

	assertContains(t, script, "DO $$ BEGIN")
	assertContains(t, script, `CREATE ROLE "outboxer" LOGIN PASSWORD NULL`)
	assertContains(t, script, `GRANT USAGE ON SCHEMA public TO "outboxer"`)
	assertContains(t, script, `GRANT SELECT, DELETE ON "events" TO "outboxer"`)
	assertContains(t, script, `GRANT UPDATE ("id") ON "events" TO "outboxer"`)
}

func TestInitScriptProducerGrants(t *testing.T) {
	cfg := baselineInitConfig()
	cfg.PGInitUser = "admin"
	cfg.PGProducerRoles = []string{"app_one", "app_two"}

	script := initScript(cfg, true)

	assertContains(t, script, `GRANT SELECT, INSERT ON "events" TO "app_one"`)
	assertContains(t, script, `GRANT SELECT, INSERT ON "events" TO "app_two"`)
}

func TestInitScriptProducerGrantsRequireInitUser(t *testing.T) {
	cfg := baselineInitConfig()
	cfg.PGProducerRoles = []string{"app_one"}

	script := initScript(cfg, true)

	assertNotContains(t, script, "app_one")
}

func TestInitScriptDLQ(t *testing.T) {
	cfg := baselineInitConfig()
	cfg.PGInitUser = "admin"
	cfg.DLQTable = "dead_letters"

	script := initScript(cfg, true)

	assertContains(t, script, `CREATE TABLE IF NOT EXISTS "dead_letters"`)
	assertContains(t, script, `"event" jsonb NOT NULL`)
	assertContains(t, script, `GRANT INSERT ON "dead_letters" TO "outboxer"`)
}

func TestInitScriptNoDLQByDefault(t *testing.T) {
	cfg := baselineInitConfig()
	cfg.PGInitUser = "admin"

	script := initScript(cfg, true)

	assertNotContains(t, script, "dead_letters")
	assertNotContains(t, script, "GRANT INSERT")
}

func TestInitScriptTriggerWhenPolling(t *testing.T) {
	cfg := baselineInitConfig()
	cfg.PollInterval = 5 * time.Second

	script := initScript(cfg, true)

	assertContains(t, script, "CREATE OR REPLACE FUNCTION outboxer_notify()")
	assertContains(t, script, "PERFORM pg_notify(TG_ARGV[0], '')")
	assertContains(t, script, `DROP TRIGGER IF EXISTS outboxer_notify ON "events"`)
	assertContains(t, script, `EXECUTE FUNCTION outboxer_notify('outboxer_events')`)
}

func TestInitScriptNoTriggerWhenNotPolling(t *testing.T) {
	script := initScript(baselineInitConfig(), true)

	assertNotContains(t, script, "outboxer_notify")
	assertNotContains(t, script, "pg_notify")
}

func TestInitPrintRedactsPassword(t *testing.T) {
	cfg := baselineInitConfig()
	cfg.PGInitUser = "admin"

	printed := initScript(cfg, true)
	assertContains(t, printed, "PASSWORD NULL")
	assertContains(t, printed, "Configure authentication for the run role separately")
	assertNotContains(t, printed, "s3cret")

	applied := initScript(cfg, false)
	assertContains(t, applied, `CREATE ROLE "outboxer" LOGIN PASSWORD 's3cret'`)
	assertNotContains(t, applied, "PASSWORD NULL")
}

func TestInitApplyEscapesPassword(t *testing.T) {
	cfg := baselineInitConfig()
	cfg.PGInitUser = "admin"
	cfg.PGPassword = "a'b"

	applied := initScript(cfg, false)
	assertContains(t, applied, `LOGIN PASSWORD 'a''b'`)
}

func TestValidateInitConfigRejectsDuplicateColumns(t *testing.T) {
	cfg := baselineInitConfig()
	cfg.EventTarget = "id" // collides with EventID

	err := validateInitConfig(cfg)
	if err == nil || !strings.Contains(err.Error(), "same column name") {
		t.Fatalf("expected duplicate column error, got %v", err)
	}
}

func TestValidateInitConfigRequiresCoreColumns(t *testing.T) {
	cfg := baselineInitConfig()
	cfg.EventTable = ""
	if err := validateInitConfig(cfg); err == nil {
		t.Fatal("expected error for missing event table")
	}
}

func TestValidateInitConfigRejectsDLQEqualsEvents(t *testing.T) {
	cfg := baselineInitConfig()
	cfg.DLQTable = cfg.EventTable
	if err := validateInitConfig(cfg); err == nil {
		t.Fatal("expected error when DLQ table equals event table")
	}
}

func TestValidateInitConfigRequiresNotifyChannelWhenPolling(t *testing.T) {
	cfg := baselineInitConfig()
	cfg.PollInterval = time.Second
	cfg.NotifyChannel = ""
	if err := validateInitConfig(cfg); err == nil {
		t.Fatal("expected error for empty notify channel while polling")
	}
}

func TestRunRejectsUnknownCommand(t *testing.T) {
	err := Run(context.Background(), []string{"bogus"})
	if err == nil || !strings.Contains(err.Error(), "unknown command") {
		t.Fatalf("expected unknown command error, got %v", err)
	}
}

func TestLoadConfigRejectsStrayArgument(t *testing.T) {
	_, err := loadConfig([]string{"stray"}, io.Discard)
	if err == nil || !strings.Contains(err.Error(), "unexpected argument") {
		t.Fatalf("expected unexpected argument error, got %v", err)
	}
}

func TestLoadInitConfigParsesApplyAndProducers(t *testing.T) {
	unsetEnv(t, "PG_INIT_USER", "PG_INIT_PASSWORD", "PG_PRODUCER_ROLES")

	cfg, apply, err := loadInitConfig([]string{"--apply", "--pg-producer-roles", "app_one, app_two"}, io.Discard)
	if err != nil {
		t.Fatalf("load init config: %v", err)
	}
	if !apply {
		t.Fatal("expected apply to be true")
	}
	if !reflect.DeepEqual(cfg.PGProducerRoles, []string{"app_one", "app_two"}) {
		t.Fatalf("unexpected producer roles: %#v", cfg.PGProducerRoles)
	}
}
